name: test
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  mongo_dart: ^0.10.3
  meta: ^1.15.0
  flutter_keyboard_visibility: ^6.0.0
  libphonenumber_plugin: ^0.3.3


  cupertino_icons: ^1.0.2
  get: ^4.6.1
  intl_phone_number_input: ^0.7.4
  numeric_keyboard: ^1.1.0
  pin_code_fields: ^8.0.1
  pin_code_view: ^0.3.0+2
  svg_flutter: ^0.0.1
  currency_picker: ^2.0.21
  url_launcher: ^6.2.6
  font_awesome_flutter: ^9.2.0
  shake: ^2.2.0
  share: ^2.0.4 
  ussd_service: ^0.1.1
  flag: ^7.0.0
  shared_preferences: ^2.2.3
  
 
 
 
  fluttertoast: ^8.0.0
  
  email_validator: ^2.1.17
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  introduction_screen: ^3.1.14
  path: ^1.9.0
  
  permission_handler: ^11.3.1
  sign_in_with_apple: ^6.1.1
  flutter_native_contact_picker: ^0.0.6
  flutter_signin_button: ^2.0.0
  
  googleapis: ^13.2.0
  path_provider: ^2.1.4

  provider: ^6.1.2
  googleapis_auth: ^1.4.1
 
  kyc_workflow: ^1.0.13
  animated_widgets: ^1.1.0
  pretty_animated_buttons: ^0.0.1
  lottie: ^3.1.2
  flutter_translate: ^4.1.0
  translator: ^1.0.0
  device_apps: ^2.2.0
  telephony: ^0.2.0
  sms_autofill: ^2.4.0

dependency_overrides:
  http: ^0.13.6
  video_player: ^2.9.1 # Ensuring the correct version is used
  whatsapp_unilink: ^2.1.0 # Ensuring the correct version is used
  meta: ^1.15.0


  

 
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/logo/
    - assets/icon/
    - assets/image/
    - assets/
    
