platform :ios, '12.0'

project 'Runner.xcworkspace'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

    
    pod 'PhoneNumberKit', '~> 3.7.6'

    flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
      config.build_settings['DEFINES_MODULE'] = 'YES'
    end
  end
end
