name: Build and Release iOS Ipa

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS Ipa
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub get
      

      - run: gem install cocoapods
    

      - run: pod repo update
        working-directory: ios

      - run: |
          echo "Manually adding flutter_keyboard_visibility to Podfile"
          echo "pod 'flutter_keyboard_visibility', :path => '.symlinks/plugins/flutter_keyboard_visibility/ios'" >> ios/Podfile
        

      - run: pod install --project-directory=ios
        
      - run: pod cache clean --all
        

      - run: flutter clean
      

      - run: flutter build ios --release --no-codesign
       

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}  # Use the secret you added
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Congrats"
