name: Build and Release iOS Ipa

on:
  workflow_dispatch:

jobs:
  build-ios:
    name: Build iOS Ipa
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - run: flutter pub upgrade

      - run: flutter pub get

      # Remove Podfile.lock and Pods directory
      - name: Remove Podfile.lock and Pods directory
        run: |
          rm -f ios/Podfile.lock
          rm -rf ios/Pods

      # Clean Derived Data
      - name: Clean Derived Data
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*

      # Recreate iOS project
      - name: Recreate iOS build files
        run: |
          rm -rf ios/
          flutter create .

      # Install CocoaPods dependencies
      - run: pod install --repo-update
        working-directory: ios

      # Modify SwiftLibphonenumberPlugin.swift
      - name: Apply Patch to SwiftLibphonenumberPlugin.swift
        run: |
          sed -i '' 's/let phoneNumberKit = PhoneNumberKit()/let phoneNumberKit = PhoneNumberKit()/g' $(find ~/.pub-cache/hosted/pub.dev/ -type f -name "SwiftLibphonenumberPlugin.swift")

      # Build iOS App
      - name: Build iOS App
        run: |
          flutter clean
          flutter build ios --release --no-codesign
          xcodebuild -workspace ios/Runner.xcworkspace \
                     -scheme Runner \
                     -sdk iphoneos \
                     -configuration Release \
                     -allowProvisioningUpdates

      - run: mkdir Payload
        working-directory: build/ios/iphoneos

      - run: mv Runner.app/ Payload
        working-directory: build/ios/iphoneos

      - name: Zip output
        run: zip -qq -r -9 FlutterIpaExport.ipa Payload
        working-directory: build/ios/iphoneos

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.PAT_TOKEN }}  # Use the secret you added
          file: build/ios/iphoneos/FlutterIpaExport.ipa
          tag: v1.0
          overwrite: true
          body: "Congrats"
